### ISSUE TITLE
Make TemporaryFolder optionally more strict

### ISSUE THREAD

**Issue by david-mas** [junit-team/junit#1001]
I think it would be a nice addition to have the option (either by some configuration parameter or by subclassing) to make the TemporaryFolder more strict. I would like it the test to fail (Assert.fail) if the temporary folder cannot be deleted, since this means the test is leaving rubbish after it.
This allows the test to be sure the streams are properly closed.

Thank you.

**Comment by marcphilipp** [comment]
Fixed by de92695.
