### ISSUE TITLE
Exceptions thrown from methodBlock() result in the failing method being unrooted in test reports

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit#1066]
The introduction of the `runLeaf()` method in `BlockJUnit4ClassRunner` in JUnit 4.9 introduces a regression with regard to exception handling. 

Consult the following versions to see the difference:

1. [BlockJUnit4ClassRunner (4.8)](https://github.com/junit-team/junit/blob/r4.8/src/main/java/org/junit/runners/BlockJUnit4ClassRunner.java)
1. [BlockJUnit4ClassRunner (4.9](https://github.com/junit-team/junit/blob/r4.9/src/main/java/org/junit/runners/BlockJUnit4ClassRunner.java)

As stated in the Javadoc for `methodBlock()`, `methodBlock()` _can be overridden in subclasses, either by overriding this method, or the implementations creating each sub-statement._

Thus, although other changes to the JUnit codebase itself in the JUnit 4.9 release do not result in an exception being thrown from `methodBlock()`, custom modifications to `methodBlock()` or the methods it invokes may in fact throw exceptions. In such cases, exceptions thrown from methodBlock() cause the current test execution to abort immediately. As a result, the failing test method is **_unrooted_** in test reports, and subsequent test methods are **never invoked**. Furthermore, RunListeners registered with JUnit are **not notified**.

The root cause is that the invocation of `methodBlock()` is no longer executed within a try-catch block as was the case in previous versions of JUnit.

A fix for this regression can be seen in recent changes to the [SpringJUnit4ClassRunner](https://github.com/spring-projects/spring-framework/commit/b81c522ee1624f3d5f170fc3468f4600956950bd) from the Spring Framework.

See also: [SPR-12613](https://jira.spring.io/browse/SPR-12613) in Spring's JIRA issue tracker.

**Comment by kcooney** [comment]
Thanks for the report. Since this bug was introduced so long ago, I'm guessing we won't do a bug-fix release for 4.12, and instead try to get a fix into 4.13

As a work-around, have your implementation of `methodBlock()` do the` try` ... `catch`, and if an exception is thrown, return a Statement that rethrows the exception.

**Comment by sbrannen** [comment]
@kcooney, did you look at the ` SpringJUnit4ClassRunner` link above?

It already does exactly what you suggested (except in the `runChild()` method in order to maintain the previous behavior). ;)

**Comment by kcooney** [comment]
@sbrannen I was just leaving the comment about the work-around in case someone finds this thread.

It's rather unfortunate that `SpringJUnit4ClassRunner` has to duplicate so much code.

**Comment by sbrannen** [comment]
> I was just leaving the comment about the work-around in case someone finds this thread.

Ahhh, OK. Thanks!

> It's rather unfortunate that `SpringJUnit4ClassRunner` has to duplicate so much code.

Yes, I couldn't agree more!

It's always been unfortunate and yet a necessity in order to properly integrate Spring's testing support into JUnit. I will attempt to elaborate more in #874.

**Comment by marcphilipp** [comment]
@sbrannen Do you have time to submit a pull request for this?

**Comment by sbrannen** [comment]
Done: pull request #1082.
