### ISSUE TITLE
Swing UI

### ISSUE THREAD

**Issue by veelenga** [junit-team/junit#1075]
Our QA team were trying to create functional framework based on JUnit. The last part was to create user interface. Here is how it looks:

![swing-runner](https://cloud.githubusercontent.com/assets/3624712/5934267/a8178fc6-a6d5-11e4-89fc-1c8421c2b4d2.PNG)

Actually the plan was to have something visually similar to [NUnit's gui] (http://www.nunit.org/index.php?p=nunit-gui&r=2.2.10)

At the moment we can adjust it to be able to use directly in junit and use "official version".

Could it be interesting for your team ? Will you merge such kind of request ?

**Comment by stefanbirkner** [comment]
Your tool is a nice add-on for JUnit. It may be useful for some users, but the majority of JUnit tests is run by a build tool or an IDE. Therefore I recommend to develop the tool independently from JUnit. You could add your tool to the list of third-party extensions that is part of our wiki.

**Comment by kcooney** [comment]
@veelenga your QA team might want to look at continuous integration systems like Travis. These products often have a nice UI. See for example https://travis-ci.org/junit-team/junit/builds/46135002

**Comment by veelenga** [comment]
@kcooney  we use old school Jenkins. Them problem is to run tests on desktop without IDEs

**Comment by veelenga** [comment]
@stefanbirkner Thanks for reply. Yeah, we will develop tool independently.
