### ISSUE TITLE
how use multiples runners at same time

### ISSUE THREAD

**Issue by tuliopessoa** [junit-team/junit#1108]
I've a class which I would like to use @RunWith(Parameterized.class) in some tests and @RunWith(Theories.class) in others, how should I do this ? There is a way to write multiple test classes ?

**Comment by kcooney** [comment]
@tuliopessoa Does this answer your question? http://stackoverflow.com/a/29202715/95725

**Comment by tuliopessoa** [comment]
I don't think so ... I want to create tests with parameters and I want be sure that all the test from that class run up to certain amount of time

**Comment by kcooney** [comment]
Could you give us a more concrete example?

**Comment by tuliopessoa** [comment]
An example could be create some objects with type Person with some parameters and see if all a sequence of test run in less than 10 seconds

**Comment by kcooney** [comment]
@tuliopessoa it sounds like you could do that without `Parameterized` or `Theories`; just use the `Timeout` Rule. But I don't think unit tests are the best way to verify that a set of operations runs in a certain period of time. If the operations are quick with no side effects, you want a microbenchmark (see https://code.google.com/p/caliper/). If they are slow or have many side effects, you want a load test.

**Comment by tuliopessoa** [comment]
Sorry, I'm quite a newbie using JUnit but to what is this runner serves for exactly ? Shouldn't a test be able to run with multiple runners ?

**Comment by kcooney** [comment]
@tuliopessoa A Rummer defines the overall.behavior of the test class. We have runners for JUnit3-style tests JUnit4-style tests, suites, paramererized tests and rheories. Runners often define other extension points (for example, most built-in runners supports `@Rule`)

You specify a runner for a test class by using the `@RunWith` annotation, so a class can have only one runner. A class can use many rules.

I find it best to.focus on the larger problem you are trying to solve. What problem are you solving that made you look.at using multiple runners?

**Comment by tuliopessoa** [comment]
The object has a life cycle, I need to be sure that it doesn't take more then 1 second and I want to use parameters to make sure I covering all the possibilities

**Comment by kcooney** [comment]
Use the `Timeout` Rule, and `@RunWith(Parameterized.class)`.

**Comment by tuliopessoa** [comment]
it worked, thanks :smile:

**Comment by legna-github** [comment]
I used the approach shown on https://bekce.github.io/junit-multiple-runwith-dependent-tests/ to combined my mockito tests (@RunWith(MockitoJUnitRunner.class)) with parameterized test (@RunWith(Parameterized.class))

worked as a charm, the only caveat i would add is that i had to make member of my outer runner (Parameterized) static in order to be accessible from the inner class runner (MockitoJUnitRunner)
