### ISSUE TITLE
Use Mockito in the internal tests

### ISSUE THREAD

**Issue by Tibor17** [junit-team/junit#1109]
We should mock every method of RunListener when testing e.g. Parameterized runner?
Of course the methods which are under Mockito proxy should imitate behavior dependning on values of method parameters.
Do you agree?

**Comment by kcooney** [comment]
Is there a specific problem in the existing tests that you are trying to address?

**Comment by Tibor17** [comment]
Yes because they are not real unit tests. Let's call it integration test, but some of them are in between.

**Comment by kcooney** [comment]
Integration tests aren't necessarily bad. The JUnit tests are fast, and testing against real objects can give confidence that the classes will work against real dependencies. Mocks are best used when either the dependency is slow, has side effects, or you need to do interaction-based tests. 

In any case, talking about this abstractly is difficult. If there are tests that can be improved with Mockito, please send us a pull request so we can discuss the change.

**Comment by Tibor17** [comment]
@kcooney 
I have to tell you the truth why I opened this issue. First of all thx for your time.
Our company has similar co to JUnit, I actually expected your answer and wanted to get confidence from big acommunity that using Mock in such code is nonsense. We don't need to test interactions, no need to isolate side effecting code and therefore Mocking a dependency behavior is just bad idea.
Sorry again for the game.

**Comment by kcooney** [comment]
@Tibor17 well, to be fair, you just received one person's opinion. I suggest searching on http://programmers.stackexchange.com/

**Comment by stefanbirkner** [comment]
I agree with @kcooney opinion. Now you have two people that are not mocking everything :-)

**Comment by kcooney** [comment]
Note that Uncle Bob appears to disagree: http://butunclebob.com/ArticleS.UncleBob.TheDangerOfMockObjects
