### ISSUE TITLE
StopWatch does not need to be Abstract

### ISSUE THREAD

**Issue by Tibor17** [junit-team/junit#1110]
The StopWatch is abstract without any abstract method. I am forced to extend this class even if not necessary.
Can we remove the modifier?

**Comment by Tibor17** [comment]
@kcooney 
@dsaff 
@marcphilipp 
@stefanbirkner 
Any thoughts?

**Comment by kcooney** [comment]
I don't have any objections.

BTW, is there a reason why you needed a quick response? You created this issue less than a day ago

**Comment by marcphilipp** [comment]
Is there a usecase when it's not necessary to extend this class?

**Comment by Tibor17** [comment]
We can commit in 4.13, no hurry; but usully you are fast to response so it looked like you did forget this.
I created StopWatch in JUnit and now I am using it in my company and wondering about the modifier. I will replace the Stopwatch in surefire with this one but `new StopWatch() {}` isn't so nice in the code.

**Comment by Tibor17** [comment]
If measuring exec time, I don't need other notifications, only reading the runtime.

**Comment by kcooney** [comment]
@Tibor17 although we often respond to issues quickly, we all have day jobs :-) If we don't respond  to issues within a few weeks, feel free to ping the issues.

**Comment by marcphilipp** [comment]
I forgot about runtime being public, never mind. No objections from me either.

**Comment by Tibor17** [comment]
The PR https://github.com/junit-team/junit/pull/1111 was created.
