### ISSUE TITLE
isTestMethod in TestSuite does not recognize @Test annotation

### ISSUE THREAD

**Issue by tkohegyi** [junit-team/junit#1139]
right now (v4.12) the isTestMethod method of TestSuite class ignores the methods those annotated with @Test, and only accepts a method as test method is it starts with "test".

Suggest to fix it in the following way:

```
private boolean isTestMethod(Method m) {
        boolean isTestAnnotated = m.isAnnotationPresent(org.junit.Test.class);
        return m.getParameterTypes().length == 0 &&
                (m.getName().startsWith("test") || isTestAnnotated) &&
                m.getReturnType().equals(Void.TYPE);
    }
```

**Comment by kcooney** [comment]
`TestSuite` is for legacy tests that don't use JUnit annotations. If your test classes use `@Test` then your test classes should not extend `junit.framework.TestCase` directly or indirectly.

In general, your classes should either import classes from `org.junit` or `junit.framework ` but not both.

**Comment by tkohegyi** [comment]
ok, thx, closing
