### ISSUE TITLE
Assert true/false with multiple conditions

### ISSUE THREAD

**Issue by alb-i986** [junit-team/junit#1151]
Say that you need to make an assertion over multiple boolean conditions, and you want them all to be true (or false).

Currently:
```
assertTrue(message1, condition1);
assertTrue(message2, condition2);
...
assertTrue(msg_n, cond_n);
```

But I want the test not to fail at the first unmet condition:
```
Def: assertTrue(boolean... conditions);
Usage: assertTrue(condition1, condition2, ..., cond_n);
```
But I would like to specify a message for each condition, in order to have a meaningful error message, in case of failure.
So maybe:
```
Def: assertTrue(SelfDescribingBoolean... conditions);
Usage: assertTrue(bool(msg1, cond1), bool(msg2, cond2)...);
```
where `bool` is a factory method for building SelfDescribingBoolean
?

I know of hamcrest's composite matcher `allOf` but it doesn't help when you want to run many matchers against many subjects (one-to-one), does it?
An alternative could probably be overloading assertThat so that it can support multiple subjects?

Thanks

**Comment by kcooney** [comment]
Does `ErrorCollector` meet your needs?

**Comment by alb-i986** [comment]
Uhm.. I don't think so.

My client code is this at the moment:
```
assertTrue("", a.xxx() && b.yyy() && c.zzz())
```

**Comment by kcooney** [comment]
To use your original example:

    @Rule public ErrorCollector collector= new ErrorCollector();

    @Test public void example() {
      // do "arrange" and "act" work

      collector.checkThat(message1, condition1, is(true));
      collector.checkThat(message2, condition2, is(true));
      collector.checkThat(message3, condition3, is(true));
    }

If any of the conditions fail, it won't stop the test. After the test runs, a combined failure will be reported.

See http://junit.org/javadoc/latest/org/junit/rules/ErrorCollector.html

**Comment by kcooney** [comment]
BTW, if you still think you would prefer to see some kind of method that allowed you to pass in multiple matchers/conditions/messages, then you probably want to file a feature request with the JavaHamcrest team.

**Comment by alb-i986** [comment]
I see, sweet, thanks.
Sorry, I just noticed addError, so I thought I had to try/catch by hand
```
try{
  assertTrue(cond1);
} catch(AssertionError e) {
  collector.addError(e);
}
```

I agree that it's probably best to leave assertTrue as it is, and play with the hamcrest matchers instead.

But this ErrorCollector is very nice.. I think it would be worth to give it more visibility by exposing it in the Assert class.

I'm thinking of a usage as follows:

```
@Test
void myTest() {
  // given ...

  // when ...

  // then
  Assert.many()
    .checkThat(...)
     ...
    .checkThat(...)
    .verify();
```

**Comment by kcooney** [comment]
We tend to avoid APIs that require method chaining (other than builders).

It is extremely challenging to write an expressive, extensible and easy to use assertion API, and what makes a good assertion API is a matter of taste. If that kind of API is something you like, I suggest an assertion framework like Truth, Fest or Hamcrest.
