### ISSUE TITLE
@Test(timeout) replaces original caller Thread

### ISSUE THREAD

**Issue by tkohegyi** [junit-team/junit#1165]
@Test(timeout = x) annotation actually replaces the running thread. 

This is not a problem in general, but in case somebody writes the test framework, (using JUnit,) that uses information in thread name or ThreadLocal, such information is lost when @Test(timeout=x) annotation is used. 
The simple @Test annotation does not cause such problem.

Would it be possible to inherit the original ThreadLocals? Or provide info on calling/original thread (that  runs JUnitCore.exec()), like adding the caller thread as ThreadLocal of the new thread created by JUnit? (The new thread is created when Future/FutureTask is used.)

**Comment by baev** [comment]
`InheritableThreadLocal` inherit information from parent thread. It would help you

**Comment by tkohegyi** [comment]
perfect, thanks
