### ISSUE TITLE
Where is org.junit.internal.runners.TestClassRunner?

### ISSUE THREAD

**Issue by smallbam** [junit-team/junit#1185]
I'm a beginner to junit. 
A piece of code from web:
import org.junit.internal.runners.TestClassRunner
I think this class should deprecated now, i guess it should be org.junit.runners.JUnit4.
But i have not sure that. can you tell me where is org.junit.internal.runners.TestClassRunner. Perhaps It  does not exist.

**Comment by kcooney** [comment]
Are you thinking of https://github.com/junit-team/junit/blob/master/src/main/java/org/junit/internal/runners/JUnit4ClassRunner.java ? If so, yes it is deprecated.

In any case, don't use any classes under "org.junit.internal". The standard runners are here:

http://junit.org/javadoc/latest/org/junit/runners/package-summary.html

There are a few other runners:

http://junit.org/javadoc/latest/org/junit/experimental/theories/Theories.html
http://junit.org/javadoc/latest/org/junit/experimental/runners/Enclosed.html
http://junit.org/javadoc/latest/org/junit/experimental/categories/Categories.html

**Comment by smallbam** [comment]
thank you very much.
