### ISSUE TITLE
JUnitCore.runClasses() and @Test(timeout)

### ISSUE THREAD

**Issue by schlagi123** [junit-team/junit#1212]
Hello I have the following code:

    public class While {
      public static void whileTrue (){
        while (true) {}
      }
    }
--------------
    import org.junit.Test;
    public class WhileTest {
      @Test(timeout = 1000)
      public void testWhileTrue() {
        While.whileTrue();
      }
    }
-------------
    import org.junit.runner.JUnitCore;
    public class RunTests {
      public static void main(String[] args) {
        JUnitCore.runClasses(WhileTest.class);
      }
    }

By running the main-method I expected, that the test-method terminat after 1000 ms. But nothing terminat. Is this a bug or is there something wrong by using the runClasses-method?

**Comment by kcooney** [comment]
That should work. Are you sure that's the complete code? If `WhileTest` extended `junit.framework.TestCase` (directly or indirectly) the `Test` annotation would be ignored.

**Comment by schlagi123** [comment]
I found out, that the main-thread terminat, but there is a new thread with the test. This thread not terminat.

**Comment by kcooney** [comment]
That is expected behavior. When you use the `Timeout` rule or the `timeout` attribute the test runs in a separate thread. Try this:

    Result result = JUnitCore.runClasses(WhileTest.class);
    System.exit(result.wasSuccessful() ? 0 : 1);

**Comment by schlagi123** [comment]
The extra thread for timed test ist ok, but i expected, that junit kill all created threads when its finished

**Comment by kcooney** [comment]
JUnit can't kill a thread that is in an infinite loop. If the test called sleep or made some other interruptible method call, it would get interrupted, which could result in the thread being killed (unless the test caught the exception).

**Comment by ahmedhamdy90** [comment]
I need to close the unterminated thread associated with the timeout at the test case. Is there anyway for doing so? Any way???

**Comment by kcooney** [comment]
@ahmedhamdy90 JUnit calls Thread.interrupt() on the test thread. If the test thread is blocking on a method that can be interrupted (usually indicated by "throws InterruptedException") then the thread should be killed. But if the test method is calling code that has an infinite loop, then there's no way to kill it.

**Comment by ahmedhamdy90** [comment]
@kcooney I built a tool that test the students'  codes online, and I really in a place that a student may have an infinite loop, my site can't be down because of a single infinite loop in a test case, there must be a way...
I am trying to get the list of running threads after the JUnit finishes, then search in each of them if it is the test case thread or not, then stop it (hack, as stop is a deprecated function). 
Can you suggest me another solution? It even seems logical to be able to kill a test case going rough.
Thanks

**Comment by kcooney** [comment]
@ahmedhamdy90  launch the tests in a separate process. If the entire test run times out, kill the subprocess.

**Comment by kcooney** [comment]
@ahmedhamdy90 You might want to consider using a continuous build system to run the tests, since they are designed for a very similar use case. You might want to try asking on stackoverflow.com (you'll likely get many more responses)
