### ISSUE TITLE
before() not being called on @Rule

### ISSUE THREAD

**Issue by StuAtGit** [junit-team/junit#1218]
I have a test that looks like this:

```
public class Test {
  @Rule
   public TemporaryFolder temp = new TemporaryFolder();
   ...
   @Before
   public void setup throws IOException {
         String outputDir = temp.getRoot().getAbsolutePath();
```

I get an IllegalStateException when it hits this case in the JUnit TemporaryFolder class:

```
    public File getRoot() {
        if(this.folder == null) {
            throw new IllegalStateException("the temporary folder has not yet been created");
        } else {
```
There was a lot of inconclusive commentary on the web, so I just debugged through the code, and took a look at the junit code.

It looks like the junit code is assuming the before() method will be called, which invokes the create() method:

```
protected void before() throws Throwable {
        this.create();
    }
```

However, when I put a breakpoint on the this.create() line - it never reaches that line. I put a breakpoint inside the constructor, and it was being hit, but the constructor just sets the two members:

```
public class TemporaryFolder extends ExternalResource {
    private final File parentFolder;
    private File folder;
```
to null:

```
   public TemporaryFolder() {
        this((File)null);
    }

    public TemporaryFolder(File parentFolder) {
        this.parentFolder = parentFolder;
    }
```

I went ahead an manually invoked the create call in my @Before:

```
   @Before
   public void setup throws IOException {
          temp.create();
         String outputDir = temp.getRoot().getAbsolutePath();
```

And everything works fine. So it does look like there is an issue with the @Rule annotation not calling the before() methods (which look like they should be invoked via the apply() and statement() methods in the ExternalResource parent class to TemporaryFile.

This is on a OpenSuse linux machine, OpenJDK 1.8.0_45, with a bytecode target of 1.7, junit 4.12 (4.11 triggered the issue as well)

I can workaround by invoking the create() method, but the documentation explicitly says it should not be called (no explanation why, though).

**Comment by kcooney** [comment]
It sounds like the rule isn't being recognized.  JUnit should call `TemporaryFolder.before()` before your `@Before` method.

Are you sure you don't have multiple versions of JUnit in your classpath? Can you create a simple reproducible test case that demonstrates the problem outside of your code base?

**Comment by StuAtGit** [comment]
When I was in the debugger, the code that was executing stepped into the JUnit 4.12 jar, so I figured that was a good indication it was executing the right code. I do have PowerMock in the classpath though (used in other tests, not this one), which I suppose could muck things up. I don't have the code handy (it's at work) - I'll take a look at before(), but I believe the problem with that is that it was not public (you can see in the comment above it's protected). I could be wrong about that. If I don't come back with a test case tomorrow, I definitely support closing this out as "someone's whacked out environment" - not worth the effort. It worked before in my environment, still works in my co-workers and our build system.. so meh.

**Comment by StuAtGit** [comment]
Although making before() public and create() protected does make much more sense to me...

**Comment by kcooney** [comment]
The `before()` method is protected because it overrides the method in `ExternalResource` (which follows the template method design pattern). You shouldn't need to call `before()` directly; it is called in the `Statement` that is returned from `apply()`

It don't know why `create()` is public. Probably only so it can be called by tests of JUnit itself.

My guess is that either there is something about your environment, or your test extends `junit.framework.TestCase`  directly bor indirectly.

**Comment by StuAtGit** [comment]
Ok. I'll poke around in my environment. The same code works in other environments, so its' something with that...

**Comment by kcooney** [comment]
@StuAtGit did you find the root cause?

**Comment by StuAtGit** [comment]
Nope. This is a work project with other, larger issues, so I may not figure this one out for a bit.

**Comment by LilooJedi** [comment]
I had the same problem with `@ClassRule` and the temp folder creation `@BeforeClass` solved it! Thanks.

**Comment by nisabhar** [comment]
I have legacy Test class which extends TestCase. I need to add ClassRule in the test class, however when I run the test case  JUnit38ClassRunner is used instead of BlockJUnit4ClassRunner . Hence my rule is not executed . I am using Maven 4.11 . If I use RunWith then my runBare method is not called at all in the test class

**Comment by kcooney** [comment]
@nisabhar classes that extend `TestCase` do not support `@Rule`. The behavior you are seeing is expected.

**Comment by ShirazMalkani** [comment]
I am having the same issue, @Rule is not executed, also @Before method is not called. I do have @BeforeEach method in the same class which is being called. any leads?

**Comment by panchenko** [comment]
@ShirazMalkani it seems like your test is executed by JUnit5, which introduced the [@BeforeEach](https://junit.org/junit5/docs/5.0.2/api/org/junit/jupiter/api/BeforeEach.html) annotation.
