### ISSUE TITLE
Assume.assumeTrue doesn't work as expected

### ISSUE THREAD

**Issue by ibrahimbeliki** [junit-team/junit#1243]
Hi.

I've wrote some cucumber tests, that I expect some of them run in some conditions.
So in the step definitions class I've added this code:

`    @Before("@WideWindow")
    public void beforeScenario() {
        Rectangle rec = GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds();
        double width = rec.getWidth();
        assumeTrue(width >= 1910);
    }`

In cucumber tests that I want to ignore, I add @WideWindow.

it works when I run the tests in intellij.

but when I run in command line "play test"

those tests which should be ignored throw exception instead:

>  failed: org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
> [error]     at feature.uiTests.audienceSection.AudienceSectionStepDefs.beforeScenario(AudienceSectionStepDefs.java:37)
> [error]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [error]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> [error]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [error]     at java.lang.reflect.Method.invoke(Method.java:606)
> [error]     at cucumber.runtime.Utils$1.call(Utils.java:37)
> [error]     at cucumber.runtime.Timeout.timeout(Timeout.java:13)
> [error]     at cucumber.runtime.Utils.invoke(Utils.java:31)
> [error]     at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
> [error]     at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:223)
> [error]     at cucumber.runtime.Runtime.runHooks(Runtime.java:211)
> [error]     at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:201)
> [error]     at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
> [error]     at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91)
> [error]     at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
> [error]     at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
> 
> 

I've read about the same issue here, but it doesn't help me: 
https://github.com/cucumber/cucumber-jvm/issues/359

I also have version 1.2.4 of cucumber-java and cucumber-junit.

Can I get some help, please? It's important for me to use it.
Thanks in advance.

**Comment by stefanbirkner** [comment]
This problem has to be fixed by Cucumber. I created a pull request for it: cucumber/cucumber-jvm#961.

**Comment by Tibor17** [comment]
@stefanbirkner right, Cucumber should properly handle `AssumptionViolatedException` but notice that JUnit is less verbose in the assertion statements than Hamcrest.
Notice this: `failed: org.junit.AssumptionViolatedException: got: , expected: is `
