### ISSUE TITLE
Can auto formation  of a string from a number in 'Parameters(name=...)' be replaced with custom format ?  

### ISSUE THREAD

**Issue by simplerun** [junit-team/junit#1244]
Posted code create results. Junit work OK.

      @Parameters(name="{index} : in {0}.{1}.{2}; out {4}.{5}.{6}; shift : {3}")
    public static Collection<Object[]> ValidDateProvider() {
    	Object[][] data = new Object[][] {
    		// day, month, year, dayIncrement, newDay , newMonth,, newYear
			new Object[] {1,1,2010,10,11,1,2010}, new Object[] {1,1,2020,35, 5,2,2020},
  I run it in Eclipse Mars 4.5.1. In junit window the list of runned tests are shown. 
But ...
Year numbers in test-parameter name is auto formated to string:
     `[0 : in 1.1.2,010; out 11.1.2,010; shift : 10]`
but I want number representing year here to be without comma separation. Like this:
     `[0 : in 1.1.2010; out 11.1.2010; shift : 10]`
Can I change this output formatting myself like in java with DecimalFormatter (instruction please) or must wait new junit release ?

**Comment by marcphilipp** [comment]
JUnit uses `MessageFormat` to convert the String pattern into the test name. Therefore, you can adjust the NumberFormat using a pattern like this: `@Parameters(name="{index} : in {0}.{1}.{2,number,#}; out {4}.{5}.{6,number,#}; shift : {3}")`.
