### ISSUE TITLE
Add easier way to provide parameters for parameterized tests

### ISSUE THREAD

**Issue by mirkoseifert** [junit-team/junit#1247]
Hi,

I'm using parameterized tests a lot, but I think that there should be an easier way to write them. Currently, one needs to add an annotation to use the `Parameterized` runner, add a static method annotated with `@Parameters` (which returns a collection of object arrays), add fields and a constructor that initializes the fields.

I'm also aware of the theories features, but I don't think it is easy to use (especially for beginners). Also, it has a different objective (I think).

I think it would be much more convenient to have a built-in annotation (e.g. 'TestData') that can be added to test methods and which supplies the parameters for the test. This could look like this:

```
@Test
@TestData({"1", "2", "3"})
@TestData({"2", "3", "5"})
public void myTestMethod(int a, int b, int expectedSum) {
   assertEquals(expectedSum, a + b);
}
```

This relieves one from writing, the constructor, the fields and the static method. Also, the relation between the test parameter values and the parameters is easier to understand (because there is no indirection using fields). Moreover, one can have individual parameters for each test method in one test class. Whether the special runner is still needed is debatable. One could even think about enabling this feature using the standard runner.

There is such an annotation in NUnit and I find it quite useful. I'm teaching TDD on a regular basis and for beginners, the creation of parameterized tests (as it is now in JUnit) is quite confusing. This is a pitty, since parameterized tests allow to easily come up with many test cases without writing a lot of code.

I'm willing to contribute the respective code, but I'd like to discuss the options here beforehand. Also, I'd like to make sure that the JUnit team considers this an extension that should be part of the framework.

There is a similar extension on Github (https://github.com/piotrturski/zohhak), but the implementation is slightly different than what I've proposed above.

What do you think?

**Comment by kcooney** [comment]
Have you seen https://github.com/Pragmatists/JUnitParams ?

Also, if you are willing to try an alpha release, https://github.com/junit-team/junit5 has other options for parameterized tests. See http://junit-team.github.io/junit5/#method-parameters-and-dependency-injection

**Comment by mirkoseifert** [comment]
Thanks for the links, JUnitParams looks nice. I will try both.
