### ISSUE TITLE
HTTP 404 for http://junit.org/news/index.htm

### ISSUE THREAD

**Issue by mjdl** [junit-team/junit#1248]
Just tried following the link to http://junit.org/news/index.htm from the FAQ question "What's the latest news on JUnit?" in the "Overview" section of the FAQ http://junit.org/faq.html

I'm not sure what the intended URL for the latest news on JUnit might be, as there is no such page linked to by the JUnit front page.

**Comment by marcphilipp** [comment]
Thanks for reporting!

There are actually quite a few broken links on that page:
![6qmhafrci6aaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/214207/13395110/d5c26554-deec-11e5-9d50-d61d8d2382ad.png)

I think we should just remove FAQ entries that only consist of a link that does not exist anymore.

**Comment by marcphilipp** [comment]
@mjdl Do you have time to prepare a pull request?

**Comment by mjdl** [comment]
I may have time today late PM EST to review links on that page and ‎revise... I will see.                                                                                                                                                                                                                                                                                                                                        Michel Joly de Lotbinière michel@lotbiniere.net                                                                                                                                                                                                                 From: Marc PhilippSent: Monday, February 29, 2016 08:03To: junit-team/junitReply To: junit-team/junitCc: MJDLSubject: Re: [junit] HTTP 404 for http://junit.org/news/index.htm (#1248)@mjdl Do you have time to prepare a pull request?

—Reply to this email directly or view it on GitHub.
