### ISSUE TITLE
org.junit.internal.MethodSorter#getDeclaredMethods should also mixin and sort super methods from clazz.getSuperclass()

### ISSUE THREAD

**Issue by AndyGee** [junit-team/junit#1249]
If a test class extends an abstract class (which could also extend an abstract class) then the current implementation fails to sort the methods from clazz.getSuperclass(). This could also be a recursive call if the superclass in turn has a superclass etc.

**Comment by kcooney** [comment]
This is intentional. All base class test methods are run before subclass test methods. Changing this behavior would break too many users' tests.
