### ISSUE TITLE
Potential bug with Assert.assertThat or CoreMatchers.hasItem

### ISSUE THREAD

**Issue by mangelo123** [junit-team/junit#1254]
I've narrowed down a test to where I believe there is a bug in either of the aforementioned methods. See code below for the scenario:

The data from the **indicators** list is just a simple db access using JPA. The **equals** and **hashCode** methods of the **Indicator** class simply use the **id** attribute.

```
        Indicator indicator2 = new Indicator();
        indicator2.setId(2);
        indicator2.setIndicatortype(indicatorType3);
        indicator2.setOrganization(org);
        indicator2.setSummary("199.188.144.155");
        indicator2.setDescription("This should be an address");
        indicator2.setRating(new BigDecimal("4.00"));
        
        List<Indicator> indicators = indService.getIndicatorsByOrganization(org, 0, 1000, getAdminUser());
        
        // This passes
        Assert.assertTrue("indicator2 should have been found", indicators.indexOf(indicator2) >= 0);        
       
        // This does not
        assertThat(indicators, hasItem(indicator2));
```

**Comment by kcooney** [comment]
I suggest stepping through the code. My guess would be that your equals() method isn't symmetric.

Note that hasItem() is a Hamcrest method, so.if this is a framework bug, then it would be a Hamcrest bug.

**Comment by mangelo123** [comment]
I got the test to pass by doing this:

```
        Address addr = new Address();
        addr.setId(2);
        addr.setIndicatortype(indicatorType3);
        addr.setOrganization(org);
        addr.setSummary("199.188.144.155");
        addr.setDescription("This should be an address");
        addr.setRating(new BigDecimal("4.00"));
                
        List<Indicator> indicators = indService.getIndicatorsByOrganization(org, 0, 1000, getAdminUser());
        
        assertThat(indicators, hasItem(addr));
```
**Address** inherits from **Indicator**. Why would `indicators.indexOf(theActualIndiator)` work and `assertThat(indicators, hasItem(addr))` not work when equals() does not  check for class equality?

**Comment by mangelo123** [comment]
Figured it out even more. Some of the descendants of Indicator did not implement equals() so it was using the inherited version (indicator) which only checked for ID.
