### ISSUE TITLE
JavaDoc for TemporaryFolder::delete() documents wrong exception type

### ISSUE THREAD

**Issue by rherrmann** [junit-team/junit#1258]
JavaDoc states that an `IllegalStateException` is thrown when the rule is unable to clean up resources. However an `AssertionError` is thrown in this case.

The same applis to the nested `Builder::assureDeletion()`.

I someone can clarify which one is right, I would try to provide a patch.

**Comment by npathai** [comment]
@rherrmann I was the one who worked on this feature. There was a discussion whether we should go with IllegalStateException or AssertionError. And finally we decided to use `AssertionError`. The javadoc is outdated as I had used IllegalStateException during initial commit.

**Comment by rherrmann** [comment]
@npathai thanks for clarifying. I have created a corresponding pull request: https://github.com/junit-team/junit/pull/1259

**Comment by marcphilipp** [comment]
Fixed by #1259.
