### ISSUE TITLE
Incompatibility of 4.9/4.10 MethodRule

### ISSUE THREAD

**Issue by KyleRogers** [junit-team/junit#357]
I'm not happy with the incompatible changes done to the built-in junit rules (Verifier for example). The problem is the removal of the MethodRule interface from those classes.

There are two problems with that:

### Upgrading from 4.8.2 to 4.9 means refactoring

If you've used the built-in rules as mentioned in their own javadoc you'll get compile errors:

```java
@Rule
public final MethodRule timeout = new Timeout(30);
```
won't compile because Timeout does not implement MethodRule anymore (but implements TestRule instead).

That is okay if you own the code but can be lot of work if you have lots of tests! Nevertheless if anyone has that issue I'd recommend refactoring to

```java
@Rule
public final Timeout timeout = new Timeout(30);
```
if you implement a library that might be used with junit pre-4.9 as well as junit 4.9 (and later).

### Libraries can't be compatible with JUnit 4.8.2 and 4.9

The above might be okay if you own the code. But imagine you're using a third party library. If the library uses the TimeoutRule or the Verifier as mentioned above, you'll have the choice between dropping the third party library or beeing stuck with junit 4.8.2 and postpone the update until the library has.

Additionally as a library developer you have to choose between supporting either JUnit 4.8.2 and below or JUnit 4.9 . You cannot support both at a time. Thats why: You cannot implement both, TestRule **and** MethodRule because that would break compatibility with 4.8.2 where TestRule does not exist. But implementing MethodRule only is no solution either: Such rules cannot be used together with the @ClassRule annotation. The RuleFieldValidator will *not* complain but those fields or methods annotated with @ClassRule and returning MethodRule implementations will not be run but will be silently ignored.

### What could be done?
The built-in rules could implement both, MethodRule and TestRule. The @ClassRule annotation should honor MethodRule as well. This would allow library developers to compile with 4.8.2 but library users could still choose between 4.8.2 or below and 4.11 or above ;-)

EDIT: The incompatible change happened from 4.8.2 to 4.9 (not from 4.9 to 4.10) - i've updated the versions in this post.

**Comment by kcooney** [comment]
Closing this. The current version of JUnit is 4.12, so incompatible changes in 4.8.2 vs 4.9 isn't a big issue anymore. Please reopen if you disagree.

**Comment by KyleRogers** [comment]
Closing issue is okay. This problem has been ignored long enough so that 4.9/4.10/4.11/4.12 all show the same incompatibility to 4.8.2 (and lower) :-/ 
Work arounds are in place to handle this issue (all our actively developed projects have upgraded JUnit to a version >= 4.9 in the past 3 years anyway)
