### ISSUE TITLE
Request to change the generics definition of Assert.assertThat

### ISSUE THREAD

**Issue by ghost** [junit-team/junit#378]
Here is the current signature of Assert.assertThat:

    public static <T> void assertThat(T actual, Matcher<? super T> matcher)

Which mean you'll get a compilation error if you try the following:

    CharSequence actual = "hello";
    String expected = "hello";
    assertThat(actual, is(expected));

That failed because `expected` (String) is a subtype of `actual` (CharSequence), which makes the generic requirement on the matcher parameter  `<? super T>` to fail.

So here I'm suggesting a solution, change the generics definition of `Assert.assertThat` to something like:

    public static <T, A extends T, E extends T> void assertThat(A actual, Matcher<E> expected)

Using this with the previous example, you get T = CharSequence, A = CharSequence, E = String, and since both CharSequence and String are subtypes of CharSequence, your program will compile fine (just like the old assertEquals).

I've also raised the same issue with hamcrest: http://code.google.com/p/hamcrest/issues/detail?id=176

**Updated 2012-02-20:**

An even simpler/better version would be this:

   `public static void assertThat(Object actual, Matcher<?> matcher)`

which removes the generics restriction all together.

**Comment by kcooney** [comment]
Note that we are considering removing our Hamcrest dependencies, so you might want to file this bug against the java-hamcrest project (https://github.com/hamcrest/hamcrest-junit)
