### ISSUE TITLE
Assert.assertArrayEquals terrible performance

### ISSUE THREAD

**Issue by amichair** [junit-team/junit#480]
Using Assert.assertArrayEquals for comparing e.g. a byte array (in JUnit 4.10, OpenJDK 1.7.0_03 on Ubuntu) has unacceptably slow performance, between one and two orders of magnitude slower than a trivial implementation of the method with the exact same contract. The difference is likely due to the fact that it uses reflection (Array.get) to get every single element of the array, boxing and all, do some irrelevant checks on the element (e.g. is it an array) etc. Instantiating a new ExactComparisonCriteria for each call even though it's a stateless class that can be reused is unnecessary as well (though likely not as bad for performance, since it's once per call, whereas the reflection stuff is once per array element per call).

In one particular test of mine that uses this assertion on byte arrays, using the built-in assertArrayEquals it takes over 15 seconds to run, whereas using a custom version of the method that does the null and length checks and just compares the arrays using a trivial loop, it runs in far less than a second. The difference is huge!

This naturally holds for all primitive arrays. float/double might be a tad longer to implement due to delta checks, but it should still be easy enough and far faster than the generic reflective implementation.

**Comment by kcooney** [comment]
This was fixed in 4.12

**Comment by amichair** [comment]
Better late than never ;-)

Thanks to everyone involved in the fix!

For reference, the fix and its discussion is in https://github.com/junit-team/junit/pull/918, which I don't see linked here. btw I like the solution - minimal code for most of the performance gain - good tradeoff imho.
