### ISSUE TITLE
ExpectedException#expect() should take Matcher<? extends Throwable> as its argument

### ISSUE THREAD

**Issue by UrsMetz** [junit-team/junit#610]
Consider the following test:

```java
...
public class WrongUsageOfExpectedExceptionApi {
    @Rule
    public ExpectedException thrown = ExpectedException.none();

    @Test
    public void wrongUsageOfExpectedExceptionApi() throws Exception {
        thrown.expect(RuntimeException.class);

        // thrown.expectMessage() should be used here
        // because an exception cannot start with a string
        thrown.expect(startsWith("some message"));
        throw new RuntimeException("some message");
    }
}
...
```

When you have something like this in a test it can be quite hard to figure out why the test fails.
At the moment `ExpectedException#expect` takes a `Matcher<?>` as its argument. By changing it to take only arguments of the type `Matcher<? extends Throwable>` the compiler could spot the mistake in the test given above.
I tried the code changes needed for the suggested change in the API with the current master (92a3f73) and all tests pass.
I understand that these changes break the API and non-generic `Matcher`s won't work with the new signature of the method but is there any other reason not to have `ExpectedException#expect` only take arguments of the type `Matcher<? extends Throwable>`?
Apart from the exclusion of non-generic `Matcher`s the only downside I see is that now you have to specify the generic type: That is you have to write for example
```
ExpectedException#expect(CoreMatchers.<Throwable>not(CoreMatchers.<Throwable>instanceOf(type)));
```
instead of
```
ExpectedException#expect(not(instanceOf(type)));
```

**Comment by kcooney** [comment]
@UrsMetz  Note that we are considering removing our Hamcrest dependencies, so you might want to file this bug against the java-hamcrest project (https://github.com/hamcrest/hamcrest-junit).

**Comment by UrsMetz** [comment]
@kcooney I re-raised this issue at hamcrest-junit: hamcrest-junit#12.
I think this issue can now be closed?

**Comment by marcphilipp** [comment]
@UrsMetz Thanks!
