### ISSUE TITLE
@DataPoints does not allow you to map Classes to Theories

### ISSUE THREAD

**Issue by bloritsch** [junit-team/junit#76]
Just to see how things map, I attempted to do something like this:

    @RunWith(Theories.class)
    public class TrackableTestCase {
      @DataPoints
      public static Class[] collectTargets() {
        Class[] targets = new Class[] {
            User.class, Incident.class
        };

        return targets;
      }

      @Theory
      public void examineClass(Class klass) {
        System.out.println(klass.getName());
      }
    }

The problem of course is that the Theories runner couldn't map the
datapoints to the Theory:
java.lang.AssertionError: Never found parameters that satisfied method
assumptions. Violated assumptions: []

When I did the same thing with Strings, I had no problems. I did find
out that the return type had to be an array and not a list. The
Theories runner just couldn't map the classes to the theory that took
the class. Additionally, when I had both the class data points and the
string data points, the Theories runner attempted to map the whole array
of strings to the examineClass theory above. Unsurprisingly there was a
class cast exception there.

**Comment by FlasH-RUS** [comment]
Just in case someone else faces it: problem appears when you `@DataPoints` method fails with exception...
Probably should behave more clear though...
