### ISSUE TITLE
Allow higher JDK version with Java compiler 1.5

### ISSUE THREAD

**Issue by Tibor17** [junit-team/junit#901]
The JDK 5 and JDK 6 are discontinued.
Allow JDK 8 which brings more features (-Xdoclint and javadoc).
Still compile all sources with Java 5 Compiler (javac -source 1.5 -target 1.5 ...).
Testing Lambda in integration tests built with Java 8: assertThat(Callable, returns...).
Enables me to use Java Service Loader from Java  6 in integration tests.

**Comment by hansjoachim** [comment]
Fwiw, there's a PR on switching to Java 1.6 for junit5 in #1064.

**Comment by marcphilipp** [comment]
I'm closing this issue. JUnit 5 will definitely use at least JDK 6 and thus allow to make use of the ServiceLoader API.

**Comment by marcphilipp** [comment]
I'm closing this issue. JUnit 5 will definitely use at least JDK 6 and thus allow to make use of the ServiceLoader API.

**Comment by marcphilipp** [comment]
I'm closing this issue. JUnit 5 will definitely use at least JDK 6 and thus allow to make use of the ServiceLoader API.

**Comment by marcphilipp** [comment]
I'm closing this issue. JUnit 5 will definitely use at least JDK 6 and thus allow to make use of the ServiceLoader API.
